# Generated by Django 5.0.1 on 2025-11-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='current_capacity',
        ),
    ]
