# Generated by Django 5.0.1 on 2025-11-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_team_current_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
