# Generated by Django 5.0.1 on 2025-11-23 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='tournaments.team'),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('player', 'team')},
        ),
    ]
