# Generated by Django 5.0.1 on 2025-11-24 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('favorite_sport', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20)),
                ('position', models.CharField(blank=True, help_text='Exemple : Attaquant, Défenseur, Gardien...', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Profil Joueur',
                'verbose_name_plural': 'Profils Joueurs',
                'db_table': 'player_profiles',
            },
        ),
    ]
