# Generated by Django 5.0.1 on 2025-11-23 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'verbose_name': 'Profil Joueur', 'verbose_name_plural': 'Profils Joueurs'},
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='favorite_sport',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to='accounts.user'),
        ),
    ]
