# Generated by Django 5.0.1 on 2025-11-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_playerprofile_options_playerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='bio',
        ),
    ]
